name: Publish Docker image
on: 
  push:
    branches: 
      - main
  pull_request:
    types: [ opened, edited, reopened ]  
    paths-ignore:
      - '.github/workflows/*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          make build-production
          make push-production
        env:
          DOCKER_BUILDKIT: 1 

      - name: Clean up
        run: docker system prune -f
  # deploy_to_vps:
  #   runs-on: ubuntu-latest
  #   needs: docker
  #   if: github.event_name == 'workflow_dispatch'
  #   steps:
  #     - name: Deploy to VPS
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.VPS_HOST }}
  #         username: ${{ secrets.VPS_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         port: ${{ secrets.VPS_PORT }}
  #         script: |
  #           docker stack deploy -c /opt/web/docker-compose.prod.yaml ms-portfolio